name: Create server
on:
  push:
    paths-ignore:
      - 'terraform/terraform-nhl.tfstate'
      - 'terraform/terraform-nhl.tfstate.backup'
    branches: [ main ]

env:
  ID_RSA: "${{ secrets.ID_RSA }}"
  TF_VAR_token: "${{ secrets.TF_token }}"

jobs:
  deploy:
    name: Create server
    runs-on: ubuntu-latest
    steps:
      - name: Init Server
        run: |
          ls -la
          make help
          make terraform-plan
