name: Create server
on:
  push:
    branches: [ main ]

env:
  ID_RSA: "${{ secrets.ID_RSA }}"
  TF_VAR_token: "${{ secrets.TF_token }}"

jobs:
  deploy:
    name: Create server
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.ID_RSA }}")
          make terraform-plan
